/* 
 * Name Entity Extraction
 *
 * The Name Entity Extraction API allows you to extract name entities from text. Name entities can be extracted from text, file or stream location. With each extracted name entity a type of entity and a probability will be given.    The flow is generally as follows:  1. Create an extraction job. If no settings are provided, default settings are used.  2. Upload content for extraction.  3. Start the extraction job.  3. Get the result when the extraction is completed.    Full API Documentation: https://docs.sphereon.com/api/extraction/name/entity/0.1/html  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Extraction.Named.Entity.Api;
using Sphereon.SDK.Extraction.Named.Entity.Model;
using Sphereon.SDK.Extraction.Named.Entity.Client;
using System.Reflection;

namespace Sphereon.SDK.Extraction.Named.Entity.Test
{
    /// <summary>
    ///  Class for testing Job
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JobTests
    {
        // TODO uncomment below to declare an instance variable for Job
        //private Job instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Job
            //instance = new Job();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Job
        /// </summary>
        [Test]
        public void JobInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Job
            //Assert.IsInstanceOfType<Job> (instance, "variable 'instance' is a Job");
        }

        /// <summary>
        /// Test the property 'CompletionTime'
        /// </summary>
        [Test]
        public void CompletionTimeTest()
        {
            // TODO unit test for the property 'CompletionTime'
        }
        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Test]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
        /// <summary>
        /// Test the property 'CreationTime'
        /// </summary>
        [Test]
        public void CreationTimeTest()
        {
            // TODO unit test for the property 'CreationTime'
        }
        /// <summary>
        /// Test the property 'Inputs'
        /// </summary>
        [Test]
        public void InputsTest()
        {
            // TODO unit test for the property 'Inputs'
        }
        /// <summary>
        /// Test the property 'JobSettings'
        /// </summary>
        [Test]
        public void JobSettingsTest()
        {
            // TODO unit test for the property 'JobSettings'
        }
        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Test]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'QueueTime'
        /// </summary>
        [Test]
        public void QueueTimeTest()
        {
            // TODO unit test for the property 'QueueTime'
        }

    }

}
