/* 
 * Name Entity Extraction
 *
 * The Name Entity Extraction API allows you to extract name entities from text. Name entities can be extracted from text, file or stream location. With each extracted name entity a type of entity and a probability will be given.    The flow is generally as follows:  1. Create an extraction job. If no settings are provided, default settings are used.  2. Upload content for extraction.  3. Start the extraction job.  3. Get the result when the extraction is completed.    Full API Documentation: https://docs.sphereon.com/api/extraction/name/entity/0.1/html  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Threading;
using NUnit.Framework;

using Sphereon.SDK.Extraction.Named.Entity.Api;
using Sphereon.SDK.Extraction.Named.Entity.Client;
using Sphereon.SDK.Extraction.Named.Entity.Model;

namespace Sphereon.SDK.Extraction.Named.Entity.Test
{
    /// <summary>
    ///  Class for testing NamedEntityExtractionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class NamedEntityExtractionApiTests
    {
        private NamedEntityExtractionApi instance;
        private static string jobid;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NamedEntityExtractionApi();
            instance.Configuration.AccessToken = "YOUR_ACCESS_TOKEN";
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NamedEntityExtractionApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NamedEntityExtractionApi
            //Assert.IsInstanceOfType(typeof(NamedEntityExtractionApi), instance, "instance is a NamedEntityExtractionApi");
        }

        /// <summary>
        /// Test CreateJob
        /// </summary>
        [Test, Order(10)]
        public void CreateJobTest()
        {
            JobSettings jobSettings = new JobSettings(JobSettings.EngineEnum.BASIC);

            var response = instance.CreateJob(jobSettings);
            Assert.IsInstanceOf<Job>(response, "response is Job");
            Assert.NotNull(response);
            Assert.AreEqual(Job.StateEnum.INPUTSUPLOADED, response.State);

            jobid = response.JobId;
        }

        /// <summary>
        /// Test AddInputText
        /// </summary>
        [Test, Order(20)]
        public void AddInputTextTest()
        {
            string text = text = "Gratis af te halen in Assen: een monumentaal kunstwerk. Er is één maar: het kunstwerk is 15 meter hoog.\n" +
                                      "Het gaat om een kunstwerk dat vanaf 1989 voor het station in Assen stond en door de Haarlemse kunstenaar Jan Jacobs Mulder is gemaakt. Het werk heet Aarde, Water, Huis en bestaat uit drie delen: een stalen sokkel met daarboven twee stalen frames.\n" +
                                      "Het kunstwerk is van de gemeente. Die verwijderde het in 2013 omdat het stationsgebied wordt heringericht, schrijft RTV Drenthe. De werkgroep Monumentale Kunst van erfgoedvereniging Heemschut kwam erachter dat het sindsdien - zo omschrijft Norman Vervat van de werkgroep - \"op een werf lag weg te roesten.\"\n" +
                                      "Plein, rotonde of verzamelaar\n" +
                                      "Assen gaat het niet terugplaatsen en vroeg de werkgroep te helpen bij het zoeken naar een ander \"tehuis\". Vervat: \"We denken aan een plein, park of rotonde. Of aan een verzamelaar met een grote tuin.\"\n" +
                                      "Hij heeft al enkele mailtjes van belangstellenden binnen. De nieuwe eigenaar moet wel over geld beschikken: het werk moet worden opgeknapt en moet bij herplaatsing een fundering krijgen (kosten: 15.000 euro). Het tienjaarlijkse onderhoud kost ook enkele duizenden euro's.";

            TextInput textInput = new TextInput(text);
            var response = instance.AddInputText(jobid, textInput);

            Assert.IsInstanceOf<Job>(response, "response is Job");
            Assert.NotNull(response);
            Assert.AreEqual(Job.StateEnum.INPUTSUPLOADED, response.State);
            Assert.AreEqual(1, response.Inputs.Count);
            Assert.AreEqual(text, response.Inputs[0].TextInput.Text);
        }

        /// <summary>
        /// Test SubmitJob
        /// </summary>
        [Test, Order(30)]
        public void SubmitJobTest()
        {
            JobSettings jobSettings = new JobSettings(JobSettings.EngineEnum.BASIC);

            var response = instance.SubmitJob(jobid, jobSettings);

            Assert.IsInstanceOf<Job>(response, "response is Job");
            Assert.NotNull(response);
            Assert.AreEqual(Job.StateEnum.PROCESSING, response.State);
        }

        /// <summary>
        /// Test GetJob
        /// </summary>
        [Test, Order(40)]
        public void GetJobTest()
        {
            var count = 0;
            Job.StateEnum state = Job.StateEnum.PROCESSING;

            // poll the state of the job until it's complete
            while (state == Job.StateEnum.PROCESSING || count < 30)
            {
                count++;
                Thread.Sleep(1000);

                var response = instance.GetJob(jobid);
                Assert.IsInstanceOf<Job>(response, "response is Job");
                Assert.NotNull(response);

                state = response.State.Value;
            }
        }

        /// <summary>
        /// Test GetResult
        /// </summary>
        [Test, Order(50)]
        public void GetResultTest()
        {
            var response = instance.GetResult(jobid);

            Assert.IsInstanceOf<NamedEntityExtractionResponse>(response, "response is KeywordExtractionResponse");
            Assert.NotNull(response);
            Assert.AreEqual(Job.StateEnum.DONE, response.Job.State);
            Assert.AreEqual(1, response.NamedEntities.Count);

            foreach (var entry in response.NamedEntities)
            {
                Console.WriteLine(entry);
            }
        }

        /// <summary>
        /// Test DeleteJob
        /// </summary>
        [Test, Order(60)]
        public void DeleteJobTest()
        {
            var response = instance.DeleteJob(jobid);

            Assert.IsInstanceOf<Job>(response, "response is Job");
            Assert.NotNull(response);
            Assert.AreEqual(Job.StateEnum.DELETED, response.State);
        }

    }

}
