/* 
 * Name Entity Extraction
 *
 * The Name Entity Extraction API allows you to extract name entities from text. Name entities can be extracted from text, file or stream location. With each extracted name entity a type of entity and a probability will be given.    The flow is generally as follows:  1. Create an extraction job. If no settings are provided, default settings are used.  2. Upload content for extraction.  3. Start the extraction job.  3. Get the result when the extraction is completed.    Full API Documentation: https://docs.sphereon.com/api/extraction/name/entity/0.1/html  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Sphereon.SDK.Extraction.Named.Entity.Client.SwaggerDateConverter;

namespace Sphereon.SDK.Extraction.Named.Entity.Model
{
    /// <summary>
    /// Name entity
    /// </summary>
    [DataContract]
    public partial class NamedEntity :  IEquatable<NamedEntity>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NamedEntity" /> class.
        /// </summary>
        /// <param name="Sentence">The sentence from which the name entity is extracted.</param>
        /// <param name="Prob">The probability that the entity is a name entity.</param>
        /// <param name="Type">The type of name entity.</param>
        /// <param name="Entity">The name entity that is extracted.</param>
        public NamedEntity(string Sentence = default(string), double? Prob = default(double?), string Type = default(string), string Entity = default(string))
        {
            this.Sentence = Sentence;
            this.Prob = Prob;
            this.Type = Type;
            this.Entity = Entity;
        }
        
        /// <summary>
        /// The sentence from which the name entity is extracted
        /// </summary>
        /// <value>The sentence from which the name entity is extracted</value>
        [DataMember(Name="sentence", EmitDefaultValue=false)]
        public string Sentence { get; set; }

        /// <summary>
        /// The probability that the entity is a name entity
        /// </summary>
        /// <value>The probability that the entity is a name entity</value>
        [DataMember(Name="prob", EmitDefaultValue=false)]
        public double? Prob { get; set; }

        /// <summary>
        /// The type of name entity
        /// </summary>
        /// <value>The type of name entity</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// The name entity that is extracted
        /// </summary>
        /// <value>The name entity that is extracted</value>
        [DataMember(Name="entity", EmitDefaultValue=false)]
        public string Entity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NamedEntity {\n");
            sb.Append("  Sentence: ").Append(Sentence).Append("\n");
            sb.Append("  Prob: ").Append(Prob).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Entity: ").Append(Entity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as NamedEntity);
        }

        /// <summary>
        /// Returns true if NamedEntity instances are equal
        /// </summary>
        /// <param name="other">Instance of NamedEntity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NamedEntity other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Sentence == other.Sentence ||
                    this.Sentence != null &&
                    this.Sentence.Equals(other.Sentence)
                ) && 
                (
                    this.Prob == other.Prob ||
                    this.Prob != null &&
                    this.Prob.Equals(other.Prob)
                ) && 
                (
                    this.Type == other.Type ||
                    this.Type != null &&
                    this.Type.Equals(other.Type)
                ) && 
                (
                    this.Entity == other.Entity ||
                    this.Entity != null &&
                    this.Entity.Equals(other.Entity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Sentence != null)
                    hash = hash * 59 + this.Sentence.GetHashCode();
                if (this.Prob != null)
                    hash = hash * 59 + this.Prob.GetHashCode();
                if (this.Type != null)
                    hash = hash * 59 + this.Type.GetHashCode();
                if (this.Entity != null)
                    hash = hash * 59 + this.Entity.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
