//
// InputEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Input entry */
open class InputEntry: Codable {

    /** The text input for a job. */
    public var textInput: TextInput?
    /** The id of the input for a job. */
    public var id: String?

    public init() {}

}
