//
// Job.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Extraction Job */
open class Job: Codable {

    public enum State: String, Codable { 
        case inputsUploaded = "INPUTS_UPLOADED"
        case processing = "PROCESSING"
        case done = "DONE"
        case error = "ERROR"
        case deleted = "DELETED"
    }
    /** The completion date/time of this job in ISO 8601 format */
    public var completionTime: Date?
    public var jobId: String?
    /** The creation date/time of this job in ISO 8601 format */
    public var creationTime: Date?
    /** The input entries */
    public var inputs: [InputEntry]?
    public var jobSettings: JobSettings?
    /** The last update date/time of this job in ISO 8601 format */
    public var updateTime: Date?
    /** The status of the job */
    public var state: State?
    /** The queue date/time of this job in ISO 8601 format */
    public var queueTime: Date?

    public init() {}

}
