//
// JobSettings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Job settings */
open class JobSettings: Codable {

    public enum Engine: String, Codable { 
        case basic = "BASIC"
    }
    /** The engine defines the quality that will be used to process the job */
    public var engine: Engine?

    public init() {}

}
