//
// NamedEntityList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Name entity list of name entities extracted from text */
open class NamedEntityList: Codable {

    /** The name entities that are extracted */
    public var namedEntities: [NamedEntity]?

    public init() {}

}
