//
// NamedEntity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Name entity */
open class NamedEntity: Codable {

    /** The sentence from which the name entity is extracted */
    public var sentence: String?
    /** The probability that the entity is a name entity */
    public var prob: Double?
    /** The type of name entity */
    public var type: String?
    /** The name entity that is extracted */
    public var entity: String?

    public init() {}

}
