//
// TextInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Text input */
open class TextInput: Codable {

    /** The text input for extraction. */
    public var text: String?

    public init() {}

}
